# Generated by Django 5.2.4 on 2025-09-22 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TrendingProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_id", models.CharField(max_length=50, unique=True)),
                ("title", models.TextField()),
                ("category", models.CharField(max_length=255)),
                ("marketplace", models.CharField(max_length=50)),
                ("current_price", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "previous_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("price_drop", models.DecimalField(decimal_places=2, max_digits=12)),
                ("url", models.URLField(max_length=2000)),
                ("image", models.URLField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
